project:
  type: website

website:
  title: "ISSS608-VAA"
  navbar:
    left:
    - text: "Hands-on Exercise"
      menu:
        - text: "Hands-on Ex 1: Programming Elegant DataViz with ggplot2"
          href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
        - text: "Hands-on Ex 2"
          href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html"
        - text: "Hands-on Ex 3"
          href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.html"
        - text: "Hands-on Ex 4"
          href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04.html"
        - text: "Hands-on Ex 5"
          href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05.html"
        - text: "Hands-on Ex 6"
          href: "Hands-on_Ex/Hands-on_Ex06/Hands-on_Ex06.html"
        - text: "Hands-on Ex 7: Visualising Geospatial Point Data"
          href: "Hands-on_Ex/Hands-on_Ex07/Hands-on_Ex07.html"
    - text: "Take-home Exercise"
      menu:
        - text: "Take-home Ex 1: Age-Sex Pyramid"
          href: "Take-home_Ex/Take-home_Ex01/Take-home_Ex01.html"
        - text: "Take-home Ex 2: ASP DataViz Makeover"
          href: "Take-home_Ex/Take-home_Ex02/Take-home_Ex02.html"
        - text: "Take-home Ex 3: VSA of Resale Flats 2022"
          href: "Take-home_Ex/Take-home_Ex03/Take-home_Ex03.html"
        - text: "Take-home Ex 4: Singapore Bi-lateral Trade"
          href: "Take-home_Ex/Take-home_Ex04/Take-home_Ex04.html"
    - text: "In-class Exercise"
      menu:
        - text: "In-class Ex 3: Interactive Data Visualization"
          href: "In-class_Ex/In-class_Ex03/In-class_Ex03.html"
        - text: "In-class Ex 4: Interactivity & Statistical Analysis"
          href: "In-class_Ex/In-class_Ex04/In-class_Ex04.html"
        - text: "In-class Ex 5a: Ternary Plots"
          href: "In-class_Ex/In-class_Ex05/In-class_Ex05a.html"
        - text: "In-class Ex 5b: Correlation Matrix"
          href: "In-class_Ex/In-class_Ex05/In-class_Ex05b.html"
        - text: "In-class Ex 5c: Heat Maps"
          href: "In-class_Ex/In-class_Ex05/In-class_Ex05c.html"
        - text: "In-class Ex 6: Time Series"
          href: "In-class_Ex/In-class_Ex06/In-class_Ex06.html"
        
    - text: "Project"
      href: "https://vaa-project8.netlify.app/"
      
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

